spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${der.datasource.driver-class-name}
    url: ${der.datasource.url}
    username: ${der.datasource.username}
    password: ${der.datasource.password}

logging:
  level:
    org:
      springframework=DEBUG: